// Always import the Component symbol from the Angular core library and annotate the component class with @Component
import { Component, OnInit } from '@angular/core';
// import Hero interface
import { Hero} from '../hero';

// three metadata properties generated by the CLI --- CSS selector, and location of the components template and css
@Component({
  selector: 'app-heroes',
  templateUrl: './heroes.component.html',
  styleUrls: ['./heroes.component.css']
})

// Angular calls ngOjnInit() shortly after creating a component GOOD PLACE FOR INITIALIZATION CODE
// return hero property of type Hero initialized with id of 1 and name `Windstorm`
export class HeroesComponent implements OnInit {
  hero: Hero = {
    id: 1,
    name: 'Windstorm'
  };

  constructor() { }

  ngOnInit(): void {
  }

}
